apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: production
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "3"
        run.googleapis.com/startup-cpu-boost: "true"

    spec:
      containers:
        - image: image
          ports:
            - containerPort: 8000
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
