apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: hello-app # If omitted, Skaffold will use the directory name by default.
profiles:
  - name: staging
    manifests:
      rawYaml:
        - run-service-staging.yaml
  - name: production
    manifests:
      rawYaml:
        - run-service-production.yaml
deploy:
  cloudrun: {}
